version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - 3306:3306
